
name: Web Automation Workflow
#bisa dirubah

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    #download repository
    - uses: actions/checkout@v3

    #setup Java
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    #Setup Browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.2.3

    # setup graldew
    - name: Setup gradlew
      run: chmod +x gradlew 
      
    # Execute gradle command for running cucumber test
    - name: Execute Test

  
